from datetime import datetime
new_series_menu_blocks = [
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"Configure your series with this menu"
    }
  },
  {
    "type":"divider"
  },
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"*TITLE*"
    }
  },
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"*My Team's Weekly Brownbag*"
    },
    "accessory":{
      "type":"button",
      "text":{
        "type":"plain_text",
        "text":"Edit Title",
        "emoji":True
      },
      "action_id":"edit_series_title",
      "value":"edit_title"
    }
  },
  {
    "type":"divider"
  },
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"*PRESENTATION*\n"
    }
  },
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"Presenter"
    },
    "accessory":{
      "type":"users_select",
      "placeholder":{
        "type":"plain_text",
        "text":"Select a user",
        "emoji":True
      },
      "action_id":"select_series_presenter"
    }
  },
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"Topic Selection"
    },
    "accessory":{
      "type":"static_select",
      "action_id":"select_topic_selection",
      "placeholder":{
        "type":"plain_text",
        "text":"Select an option",
        "emoji":True
      },
      "options":[
        {
          "text":{
            "type":"plain_text",
            "text":"Pre-determined",
            "emoji":True
          },
          "value":"pre-determined"
        },
        {
          "text":{
            "type":"plain_text",
            "text":"Presenter's choice",
            "emoji":True
          },
          "value":"presenter_choice"
        }
      ]
    }
  },
  {
    "type":"divider"
  },
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"*SCHEDULE*"
    }
  },
  {
    "type":"actions",
    "elements":[
      {
        "type":"datepicker",
        # Get today's date
        "initial_date":datetime.today().date().strftime("%Y-%m-%d"),
        "action_id":"pick_series_date",
        "placeholder":{
          "type":"plain_text",
          "text":"Select a date",
          "emoji":True
        }
      },
      {
        "type":"static_select",
        "action_id":"select_series_time",
        "placeholder":{
          "type":"plain_text",
          "text":"Select a time",
          "emoji":True
        },
        "options":[
          {
            "text":{
              "type":"plain_text",
              "text":"12:00 AM",
              "emoji":True
            },
            "value":"time-0000"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12:15 AM",
              "emoji":True
            },
            "value":"time-0015"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12:30 AM",
              "emoji":True
            },
            "value":"time-0030"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12:45 AM",
              "emoji":True
            },
            "value":"time-0045"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:00 AM",
              "emoji":True
            },
            "value":"time-0100"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:15 AM",
              "emoji":True
            },
            "value":"time-0115"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:30 AM",
              "emoji":True
            },
            "value":"time-0130"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:45 AM",
              "emoji":True
            },
            "value":"time-0145"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:00 AM",
              "emoji":True
            },
            "value":"time-0200"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:15 AM",
              "emoji":True
            },
            "value":"time-0215"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:30 AM",
              "emoji":True
            },
            "value":"time-0230"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:45 AM",
              "emoji":True
            },
            "value":"time-0245"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:00 AM",
              "emoji":True
            },
            "value":"time-0300"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:15 AM",
              "emoji":True
            },
            "value":"time-0315"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:30 AM",
              "emoji":True
            },
            "value":"time-0330"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:45 AM",
              "emoji":True
            },
            "value":"time-0345"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:00 AM",
              "emoji":True
            },
            "value":"time-0400"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:15 AM",
              "emoji":True
            },
            "value":"time-0415"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:30 AM",
              "emoji":True
            },
            "value":"time-0430"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:45 AM",
              "emoji":True
            },
            "value":"time-0445"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:00 AM",
              "emoji":True
            },
            "value":"time-0500"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:15 AM",
              "emoji":True
            },
            "value":"time-0515"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:30 AM",
              "emoji":True
            },
            "value":"time-0530"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:45 AM",
              "emoji":True
            },
            "value":"time-0545"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:00 AM",
              "emoji":True
            },
            "value":"time-0600"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:15 AM",
              "emoji":True
            },
            "value":"time-0615"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:30 AM",
              "emoji":True
            },
            "value":"time-0630"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:45 AM",
              "emoji":True
            },
            "value":"time-0645"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:00 AM",
              "emoji":True
            },
            "value":"time-0700"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:15 AM",
              "emoji":True
            },
            "value":"time-0715"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:30 AM",
              "emoji":True
            },
            "value":"time-0730"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:45 AM",
              "emoji":True
            },
            "value":"time-0745"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:00 AM",
              "emoji":True
            },
            "value":"time-0800"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:15 AM",
              "emoji":True
            },
            "value":"time-0815"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:30 AM",
              "emoji":True
            },
            "value":"time-0830"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:45 AM",
              "emoji":True
            },
            "value":"time-0845"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:00 AM",
              "emoji":True
            },
            "value":"time-0900"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:15 AM",
              "emoji":True
            },
            "value":"time-0915"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:30 AM",
              "emoji":True
            },
            "value":"time-0930"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:45 AM",
              "emoji":True
            },
            "value":"time-0945"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:00 AM",
              "emoji":True
            },
            "value":"time-1000"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:15 AM",
              "emoji":True
            },
            "value":"time-1015"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:30 AM",
              "emoji":True
            },
            "value":"time-1030"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:45 AM",
              "emoji":True
            },
            "value":"time-1045"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:00 AM",
              "emoji":True
            },
            "value":"time-1100"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:15 AM",
              "emoji":True
            },
            "value":"time-1115"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:30 AM",
              "emoji":True
            },
            "value":"time-1130"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:45 AM",
              "emoji":True
            },
            "value":"time-1145"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12:00 PM",
              "emoji":True
            },
            "value":"time-1100"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12:15 PM",
              "emoji":True
            },
            "value":"time-1115"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12:30 PM",
              "emoji":True
            },
            "value":"time-1130"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12:45 PM",
              "emoji":True
            },
            "value":"time-1145"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:00 PM",
              "emoji":True
            },
            "value":"time-1300"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:15 PM",
              "emoji":True
            },
            "value":"time-1315"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:30 PM",
              "emoji":True
            },
            "value":"time-1330"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"1:45 PM",
              "emoji":True
            },
            "value":"time-1345"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:00 PM",
              "emoji":True
            },
            "value":"time-1400"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:15 PM",
              "emoji":True
            },
            "value":"time-1415"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:30 PM",
              "emoji":True
            },
            "value":"time-1430"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2:45 PM",
              "emoji":True
            },
            "value":"time-1445"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:00 PM",
              "emoji":True
            },
            "value":"time-1500"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:15 PM",
              "emoji":True
            },
            "value":"time-1515"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:30 PM",
              "emoji":True
            },
            "value":"time-1530"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3:45 PM",
              "emoji":True
            },
            "value":"time-1545"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:00 PM",
              "emoji":True
            },
            "value":"time-1600"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:15 PM",
              "emoji":True
            },
            "value":"time-1615"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:30 PM",
              "emoji":True
            },
            "value":"time-1630"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4:45 PM",
              "emoji":True
            },
            "value":"time-1645"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:00 PM",
              "emoji":True
            },
            "value":"time-1700"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:15 PM",
              "emoji":True
            },
            "value":"time-1715"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:30 PM",
              "emoji":True
            },
            "value":"time-1730"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5:45 PM",
              "emoji":True
            },
            "value":"time-1745"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:00 PM",
              "emoji":True
            },
            "value":"time-1800"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:15 PM",
              "emoji":True
            },
            "value":"time-1815"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:30 PM",
              "emoji":True
            },
            "value":"time-1830"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6:45 PM",
              "emoji":True
            },
            "value":"time-1845"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:00 PM",
              "emoji":True
            },
            "value":"time-1900"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:15 PM",
              "emoji":True
            },
            "value":"time-1915"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:30 PM",
              "emoji":True
            },
            "value":"time-1930"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7:45 PM",
              "emoji":True
            },
            "value":"time-1945"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:00 PM",
              "emoji":True
            },
            "value":"time-2000"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:15 PM",
              "emoji":True
            },
            "value":"time-2015"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:30 PM",
              "emoji":True
            },
            "value":"time-2030"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8:45 PM",
              "emoji":True
            },
            "value":"time-2045"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:00 PM",
              "emoji":True
            },
            "value":"time-2100"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:15 PM",
              "emoji":True
            },
            "value":"time-2115"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:30 PM",
              "emoji":True
            },
            "value":"time-2130"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9:45 PM",
              "emoji":True
            },
            "value":"time-2145"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:00 PM",
              "emoji":True
            },
            "value":"time-2200"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:15 PM",
              "emoji":True
            },
            "value":"time-2215"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:30 PM",
              "emoji":True
            },
            "value":"time-2230"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10:45 PM",
              "emoji":True
            },
            "value":"time-2245"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:00 PM",
              "emoji":True
            },
            "value":"time-2300"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:15 PM",
              "emoji":True
            },
            "value":"time-2315"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:30 PM",
              "emoji":True
            },
            "value":"time-2330"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11:45 PM",
              "emoji":True
            },
            "value":"time-2345"
          }
        ]
      }
    ]
  },
  {
    "type":"actions",
    "elements":[
      {
        "type":"static_select",
        "action_id":"select_series_frequency",
        "placeholder":{
          "type":"plain_text",
          "text":"Frequency",
          "emoji":True
        },
        "options":[
          {
            "text":{
              "type":"plain_text",
              "text":"Every Day",
              "emoji":True
            },
            "value":"every-day"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"Every Weekday",
              "emoji":True
            },
            "value":"every-weekday"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"Every 2 Weeks",
              "emoji":True
            },
            "value":"every-2-weeks"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"Every 3 Weeks",
              "emoji":True
            },
            "value":"every-3-weeks"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"Every Month",
              "emoji":True
            },
            "value":"every-month"
          }
        ]
      },
      {
        "type":"static_select",
        "action_id":"select_series_numsessions",
        "placeholder":{
          "type":"plain_text",
          "text":"Number of Sessions",
          "emoji":True
        },
        "options":[
          {
            "text":{
              "type":"plain_text",
              "text":"1",
              "emoji":True
            },
            "value":"numsessions-1"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"2",
              "emoji":True
            },
            "value":"numsessions-2"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"3",
              "emoji":True
            },
            "value":"numsessions-3"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"4",
              "emoji":True
            },
            "value":"numsessions-4"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"5",
              "emoji":True
            },
            "value":"numsessions-5"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"6",
              "emoji":True
            },
            "value":"numsessions-6"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"7",
              "emoji":True
            },
            "value":"numsessions-7"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"8",
              "emoji":True
            },
            "value":"numsessions-8"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"9",
              "emoji":True
            },
            "value":"numsessions-9"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"10",
              "emoji":True
            },
            "value":"numsessions-10"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"11",
              "emoji":True
            },
            "value":"numsessions-11"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"12",
              "emoji":True
            },
            "value":"numsessions-12"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"13",
              "emoji":True
            },
            "value":"numsessions-13"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"14",
              "emoji":True
            },
            "value":"numsessions-14"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"15",
              "emoji":True
            },
            "value":"numsessions-15"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"16",
              "emoji":True
            },
            "value":"numsessions-16"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"17",
              "emoji":True
            },
            "value":"numsessions-17"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"18",
              "emoji":True
            },
            "value":"numsessions-18"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"19",
              "emoji":True
            },
            "value":"numsessions-19"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"20",
              "emoji":True
            },
            "value":"numsessions-20"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"21",
              "emoji":True
            },
            "value":"numsessions-21"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"22",
              "emoji":True
            },
            "value":"numsessions-22"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"23",
              "emoji":True
            },
            "value":"numsessions-23"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"24",
              "emoji":True
            },
            "value":"numsessions-24"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"25",
              "emoji":True
            },
            "value":"numsessions-25"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"26",
              "emoji":True
            },
            "value":"numsessions-26"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"27",
              "emoji":True
            },
            "value":"numsessions-27"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"28",
              "emoji":True
            },
            "value":"numsessions-28"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"29",
              "emoji":True
            },
            "value":"numsessions-29"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"30",
              "emoji":True
            },
            "value":"numsessions-30"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"31",
              "emoji":True
            },
            "value":"numsessions-31"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"32",
              "emoji":True
            },
            "value":"numsessions-32"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"33",
              "emoji":True
            },
            "value":"numsessions-33"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"34",
              "emoji":True
            },
            "value":"numsessions-34"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"35",
              "emoji":True
            },
            "value":"numsessions-35"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"36",
              "emoji":True
            },
            "value":"numsessions-36"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"37",
              "emoji":True
            },
            "value":"numsessions-37"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"38",
              "emoji":True
            },
            "value":"numsessions-38"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"39",
              "emoji":True
            },
            "value":"numsessions-39"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"40",
              "emoji":True
            },
            "value":"numsessions-40"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"41",
              "emoji":True
            },
            "value":"numsessions-41"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"42",
              "emoji":True
            },
            "value":"numsessions-42"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"43",
              "emoji":True
            },
            "value":"numsessions-43"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"44",
              "emoji":True
            },
            "value":"numsessions-44"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"45",
              "emoji":True
            },
            "value":"numsessions-45"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"46",
              "emoji":True
            },
            "value":"numsessions-46"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"47",
              "emoji":True
            },
            "value":"numsessions-47"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"48",
              "emoji":True
            },
            "value":"numsessions-48"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"49",
              "emoji":True
            },
            "value":"numsessions-49"
          },
          {
            "text":{
              "type":"plain_text",
              "text":"50",
              "emoji":True
            },
            "value":"numsessions-50"
          }
        ]
      }
    ]
  },
  {
    "type":"divider"
  },
  {
    "type":"section",
    "text":{
      "type":"mrkdwn",
      "text":"*SUMMARY*"
    }
  },
  {
    "type":"context",
    "elements":[
      {
        "type":"mrkdwn",
        "text":"*Title*: My Team's Weekly Brownbag"
      },
      {
        "type":"mrkdwn",
        "text":"*Presenter*: Not Selected"
      },
      {
        "type":"mrkdwn",
        "text":"*Topic Selection*: Not Selected"
      },
      {
        "type":"mrkdwn",
        "text":"*First Session*: Not Selected"
      },
      {
        "type":"mrkdwn",
        "text":"*Time*: Not Selected"
      },
      {
        "type":"mrkdwn",
        "text":"*Frequency*: Not Selected"
      },
      {
        "type":"mrkdwn",
        "text":"*Last Session*: N/A"
      }
    ]
  },
  {
    "type":"actions",
    "elements":[
      {
        "type":"button",
        "action_id":"cancel_series",
        "text":{
          "type":"plain_text",
          "text":"Cancel",
          "emoji":True
        },
        "value":"cancel"
      }
    ]
  }
]